# -*- coding: utf-8 -*-
"""claseData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_AHciQ1gbHAhDygJI5YlJLvUDCu9dCo
"""

import numpy as np

array_basico = np.array([1, 2, 3, 4, 5])
array_basico

array_basico[0]

array_basico[0]=10
array_basico

array_basico*2

print(array_basico.min())
print(array_basico.max())
print(array_basico.sum())

array_basico[2:]

array_basico[:2]

array_basico[:]=99
array_basico

array_bidimensional = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array_bidimensional)

array_bidimensional = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(array_bidimensional)

array_bidimensional[:2,1:]

array_bidimensional[:3,2:]

print(array_bidimensional.min())
print(array_bidimensional.max())
print(array_bidimensional.sum())

print(array_bidimensional.max(axis = 0))



print(array_bidimensional.max(axis = 1))

import pandas as pd

football_dic = {
    "player": ["lionel messi", "cristiano ronaldo"],
    "year":[2016, 2016],
    "goals":[37,25]
}

data = pd.DataFrame(football_dic)
print(data)

from google.colab import drive
drive.mount('/content/drive/')

url="/content/drive/MyDrive/AAPL.csv"
df=pd.read_csv(url, sep=",", header=1)
print(df.head())

df.tail(10)

df.sample(10)

df.shape

df.size

df.info()

df.describe()

df.columns

df.columns = ['tem', 'AAPL', 'AAPL.1', 'AAPL.2', 'AAPL.3', 'AAPL.4', 'AAPL.5']
print(df.info())

print(df.info())
print(df ['tem'])
print(df['temp'].unique())
print(df['temp'].count())
print(df['temp'].value_counts())

